"""add hierarchy foreign key indexes

Revision ID: 0b543b737a18
Revises: 85c9a83351b5
Create Date: 2026-08-22 18:51:49.866994

"""
from typing import Sequence, Union

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '0b543b737a18'
down_revision: Union[str, Sequence[str], None] = '85c9a83351b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_areas_site_id'), 'areas', ['site_id'], unique=False)
    op.create_index(op.f('ix_machines_area_id'), 'machines', ['area_id'], unique=False)
    op.create_index(op.f('ix_machines_production_line_id'), 'machines', ['production_line_id'], unique=False)
    op.create_index(op.f('ix_production_lines_area_id'), 'production_lines', ['area_id'], unique=False)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_index(op.f('ix_production_lines_area_id'), table_name='production_lines')
    op.drop_index(op.f('ix_machines_production_line_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_area_id'), table_name='machines')
    op.drop_index(op.f('ix_areas_site_id'), table_name='areas')
    # ### end Alembic commands ###
