"""add ai processing state

Revision ID: 204d569650e2
Revises: bab06a78f698
Create Date: 2026-08-24 05:29:56.595898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204d569650e2'
down_revision: Union[str, Sequence[str], None] = 'bab06a78f698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_processing_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_reading_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('first_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(
        ["source_reading_id"],
        ["sensor_readings.id"],
        name="fk_ai_processing_states_source_reading_id",
        ondelete="CASCADE",
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_ai_processing_states_reading_model_version', 'ai_processing_states', ['source_reading_id', 'model_name', 'model_version'], unique=True, postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_ai_processing_states_reading_model_version', table_name='ai_processing_states', postgresql_nulls_not_distinct=True)
    op.drop_table('ai_processing_states')
    # ### end Alembic commands ###
