"""add production runs and downtime events

Revision ID: 58633c31421f
Revises: 204d569650e2
Create Date: 2026-08-25 02:09:26.073906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58633c31421f'
down_revision: Union[str, Sequence[str], None] = '204d569650e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'status',
        sa.String(length=30),
        server_default='running',
        nullable=False,
    ),  
    sa.Column('target_quantity', sa.Integer(), nullable=True),
    sa.Column(
        'total_quantity',
        sa.Integer(),
        server_default='0',
        nullable=False,
    ),
    sa.Column(
        'good_quantity',
        sa.Integer(),
        server_default='0',
        nullable=False,
    ),
    sa.Column(
        'reject_quantity',
        sa.Integer(),
        server_default='0',
        nullable=False,
    ),
    sa.Column('ideal_cycle_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], name='fk_production_runs_production_line_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_runs_production_line_id'), 'production_runs', ['production_line_id'], unique=False)
    op.create_table('downtime_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_run_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name='fk_downtime_events_machine_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], name='fk_downtime_events_production_run_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downtime_events_machine_id'), 'downtime_events', ['machine_id'], unique=False)
    op.create_index(op.f('ix_downtime_events_production_run_id'), 'downtime_events', ['production_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downtime_events_production_run_id'), table_name='downtime_events')
    op.drop_index(op.f('ix_downtime_events_machine_id'), table_name='downtime_events')
    op.drop_table('downtime_events')
    op.drop_index(op.f('ix_production_runs_production_line_id'), table_name='production_runs')
    op.drop_table('production_runs')
    # ### end Alembic commands ###
