"""require machine area

Revision ID: 85c9a83351b5
Revises: 60a98459d249
Create Date: 2026-08-20 03:28:18.637426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c9a83351b5'
down_revision: Union[str, Sequence[str], None] = '60a98459d249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
