"""add sensor ai configuration

Revision ID: e35fae4e7e30
Revises: 518a97cf035b
Create Date: 2026-08-23 22:01:06.891561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35fae4e7e30'
down_revision: Union[str, Sequence[str], None] = '518a97cf035b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_ai_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('engine_name', sa.String(length=100), nullable=False),
    sa.Column('anomaly_threshold', sa.Float(), nullable=False),
    sa.Column('min_history', sa.Integer(), nullable=False),
    sa.Column('history_limit', sa.Integer(), nullable=False),
    sa.Column('high_risk_threshold', sa.Float(), nullable=False),
    sa.Column('critical_risk_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ["sensor_id"],
        ["sensors.id"],
        name="fk_sensor_ai_configs_sensor_id",
        ondelete="CASCADE",
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint(
        "sensor_id",
        name="uq_sensor_ai_configs_sensor_id",
    )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_ai_configs')
    # ### end Alembic commands ###
